package test.livedata.includes;

public class Key {
    public static final String PREFS = "prefs";
    public static final String AUTH_PREFS = "auth_prefs";
    public static final String AUTH_TOKEN = "auth_token";
    public static final String URL = "url";
    public static final String PAGE_TITLE = "page_title";
    public static final String ID = "id";
    public static final String TITLE = "name";
    public static final String NAME = "name";
    public static final String DESC = "desc";
    public static final String IMAGES = "images";
    public static final String POSITION = "position";
    public static final String USER_BIRTHDATE = "user_birthdate";
    public static final String USER_GENDER = "user_gender";
    public static final String USER_EMAIL = "user_email";
    public static final String USER_NAME = "user_name";
    public static final String USER_FIRST_NAME = "user_first_name";
    public static final String USER_LAST_NAME = "user_last_name";
    public static final String USER_SOCIAL_ID = "user_social_id";
    public static final String USER_SOCIAL_TYPE = "user_social_type";
    public static final String USER_SOCIAL_TOKEN = "user_social_token";
    public static final String USER_TOKEN = "user_token";
    public static final String USER_ID = "user_id";
    public static final String DATA = "data";
    public static final String PUSH_TOKEN = "push_token";
    public static final String IS_PUSH_TOKEN_SENT = "is_push_token_sent";
    public static final String LANGUAGE = "language";
    public static final String SOCKET_NEW_MESSAGE = "NEW_MESSAGE";
    public static final String SOCKET_SEND_MESSAGE = "SEND_MESSAGE";
    public static final String SOCKET_DELIVERED_MESSAGE = "DELIVERED";
    public static final String SOCKET_RECEIVED_MESSAGE = "RECEIVED";
    public static final String USER_INFO = "user_info";
    public static final String USER_PHOTO = "user_photo";
    public static final String SETTINGS_SEARCH_GENDER = "settings_search_gender";
    public static final String SETTINGS_SEARCH_RADIUS = "settings_search_radius";
    public static final String SETTINGS_SEARCH_SPORT_IDS = "settings_search_sport_ids";
    public static final String SETTINGS_SEARCH_SPORTS = "settings_notify_user_likes";
    public static final String USER_DATA = "user_data";
    public static final String LEARNED_SWIPE_RIGHT = "learned_swipe_right";
    public static final String LEARNED_SWIPE_LEFT = "learned_swipe_left";
    public static final String CACHE_LIKED_ME = "cache_liked_me";
    public static final String IS_PROFILE_COMPLETE = "is_profile_complete";
    public static final String MATCHED_USER_DATA = "matched_user_data";
    public static final String RETURN_TO_CARDS = "return_to_cards";
    public static final String INSTA_CONNECTTION = "insta_connection";
    public static final String DEVICE_ID = "device_id";
    public static final String DEVICE_ID_SET = "device_id_set";
    public static final String PHOTOS = "photos";
    public static final String COUNT = "count";
    public static final String REMAINING_ITEMS = "remaining_items";
    public static final String RATED_APP = "user_rated_app";
    public static final String TO_WRITE = "action_write";
    public static final String PLACES_CACHE = "places_cache";
    public static final String MY_SPORT_IDS = "my_sport_ids";
    public static final String SETTINGS_SEARCH_DAYS = "settings_search_days";
    public static final String SETTINGS_SEARCH_FROM = "settings_search_from";
    public static final String SETTINGS_SEARCH_TO = "settings_search_to";
    public static final String EVENT_NAME = "event_name";
    public static final String FACEBOOK_ID = "facebookId";
    public static final String SPORTS_CACHE = "sports_cache";
    public static final String COUNTRIES_CACHE = "countries_cache";
    public static final String CITIES_CACHE = "cities_cache";
    public static final String COUNTRY_ID = "country_id";
    public static final String CITY_ID = "city_id";
    public static final String LOCATION_PREFS = "location_prefs";
    public static final String TIME = "time";
    public static final String LATITUDE = "latitude";
    public static final String LONGITUDE = "longitude";
    public static final String BEARING = "bearing";
    public static final String MIN_AGE = "min_age";
    public static final String MAX_AGE = "max_age";
    public static final String PLAYERS_COUNT = "players_count";
    public static final String EVENT_ID = "event_id";
    public static final String ONLY_MINE = "only_mine";
    public static final String CODE = "code";
    public static final String EVENT_FILTER = "event_filter";
    public static final String EVENT = "event";
    public static final String IS_SAVED_STATE = "is_saved_state";
    public static final String SESSION_EXPIRED = "session_expired";
    public static final String UPDATE_MY_EVENTS = "update_my_events";
    public static final String CREATED_EVENTS_COUNT = "created_events_count";
    public static final String APPLIED_EVENTS_COUNT = "applied_events_count";
    public static final String JOINED_EVENTS_COUNT = "joined_events_count";
    public static final String NOTIFICATION_TYPE = "notification_type";
    public static final String EVENT_APPLICATION_REQUEST = "event_application_request";
    public static final String EVENT_APPLICATION_ACCEPT = "event_application_accept";
    public static final String EVENT_APPLICATION_DECLINE = "event_application_decline";
    public static final String EVENT_CANCEL = "EVENT_CANCEL";
    public static final String EVENT_NOTIFICATION = "EVENT_NOTIFICATION";
    public static final String INTENT_EXTRAS = "intent_extras";

    public static final String PHONE_NUMBER = "username";
    public static final String LAST_AUTH_DATE = "last_auth_date";
    public static final String LAST_AD_SHOWN_DATE = "last_ad_shown_date";
    public static final String BALANCE_UPDATED_AT_MILLIS = "updated_at_millis";
    public static final String EVENTS = "events";
    public static final String UNREAD_EVENTS_COUNT = "unread_events_count";
    public static final String CAR_PHOTO_REQUIRED = "car_photo_required";
    public static final String ID_PHOTO_REQUIRED = "id_photo_required";
    public static final String TP_PHOTO_REQUIRED = "tp_photo_required";
    public static final String ACTION_EXIT = "action_exit";

    public static final String FREE_WAITING_MINUTES = "free_waiting_minutes";

    public static final String INITIAL_PRICE = "initial_price";
    public static final String BOARD_INITIAL_PRICE = "board_initial_price";

    public static final String KM_PRICE = "for_km";
    public static final String BOARD_FOR_KM = "board_for_km";
    public static final String BOARD_TARIFF_ID = "board_tariff_id";

    public static final String WAIT_PRICE = "wait_price";

    public static final String TOTAL_PRICE = "total_price";
    public static final String TOTAL_DISTANCE = "total_distance";

    public static final String TIME_PRICE_FOR_MINUTE = "time_price_for_minute";

    public static final String ORDER_SKIP_TIME = "order_skip_time";
    public static final String STATUS_TOGGLE = "status_toggle";

    public static final String STORED_ORDER_PREFS = "order_save_preferences";
    public static final String ORDER_ID = "customer_id";
    public static final String ORDER_STATUS = "order_status";
    public static final String LAST_PROBKA_SENT_DATE = "last_probka_sent_date";
    public static final String LAST_SERVER_LOCATION_SENT_DATE = "last_server_location_sent_date";

    public static final String DOPLATA_VERSION = "doplata_version";
    public static final String TARIFFS = "tariffs";

    public static final String TARIFF_PREFS = "tariff_prefs";
    public static final String CITY_PREFS_KEYS = "city_prefs";

    public static final String ORDER_TARIFF_ID = "order_tariff_id";
    public static final String _TARIFF_INITIAL_PRICE = "_tariff_initial_price";
    public static final String _TARIFF_KM_PRICE = "_tariff_km_price";
    public static final String _ADDITIONAL_SETTINGS = "_tariff_additional_settings";
    public static final String DOPLATA_REGIONS_STRINGS = "doplata_regions_strings";
    public static final String TARIFFS_STRINGS = "tariffs_strings";
    public static final String LAST_ACTIVITY_NAME = "last_activity_name";

    public static final String GPS_SOUNDS = "gps_sounds";
    public static final String INTERNET_SOUNDS = "internet_sounds";
    public static final String USER_TYPE = "user_type";

    public static final String PASSWORD = "password";

    public static final String LAST_LOCATION_PREFS = "my_last_location_prefs";
    public static final String LAST_LOCATION_PROVIDER = "last_location_provider";
    public static final String LAST_LOCATION_LAT = "lastLocation_lat";
    public static final String LAST_LOCATION_LNG = "lastLocation_lng";
    public static final String LAST_LOCATION_BEARING = "lastLocation_bearing";
    public static final String LAST_LOCATION_SPEED = "lastLocation_speed";
    public static final String LAST_LOCATION_ACCURACY = "lastLocation_accuracy";
    public static final String LAST_LOCATION_TIME = "lastLocation_time";
    public static final String DEVICE_NAME = "device_name";
    public static final String CLICK_HAVE_CODE = "click_have_code";
    public static final String REFRESH_CONTENT = "refresh_content";
    public static final String SHOW_LOADING = "show_loading";
    public static final String HIDE_LOADING = "hide_loading";
    public static final String CONNECTION_ERROR = "connection_error";
    public static final String CREATE_RANDOM_GIFT = "create_random_gift";
    public static final String LOG_KEY = "BFJBNSOIVNO";
    public static final String JS_EVAL = "js_eval";

    public static final String BG_NEWS_APPS_IMG_URL = "bg_news_apps_img_url";
    public static final String BG_NEWS_APPS_GRADIENT_ANGLE = "bg_news_apps_gradient_angle";
    public static final String BG_NEWS_APPS_GRADIENT_START_COLOR = "bg_news_apps_gradient_start_color";
    public static final String BG_NEWS_APPS_GRADIENT_CENTER_COLOR = "bg_news_apps_gradient_center_color";
    public static final String BG_NEWS_APPS_GRADIENT_END_COLOR = "bg_news_apps_gradient_end_color";

    public static final String BG_MEGACOM_APPS_IMG_URL = "bg_megacom_apps_img_url";
    public static final String BG_MEGACOM_APPS_GRADIENT_ANGLE = "bg_megacom_apps_gradient_angle";
    public static final String BG_MEGACOM_APPS_GRADIENT_START_COLOR = "bg_megacom_apps_gradient_start_color";
    public static final String BG_MEGACOM_APPS_GRADIENT_CENTER_COLOR = "bg_megacom_apps_gradient_center_color";
    public static final String BG_MEGACOM_APPS_GRADIENT_END_COLOR = "bg_megacom_apps_gradient_end_color";

    public static final String BG_WEB_APPS_IMG_URL = "bg_web_apps_img_url";
    public static final String BG_WEB_APPS_GRADIENT_ANGLE = "bg_web_apps_gradient_angle";
    public static final String BG_WEB_APPS_GRADIENT_START_COLOR = "bg_web_apps_gradient_start_color";
    public static final String BG_WEB_APPS_GRADIENT_CENTER_COLOR = "bg_web_apps_gradient_center_color";
    public static final String BG_WEB_APPS_GRADIENT_END_COLOR = "bg_web_apps_gradient_end_color";

    public static final String USER_FULL_BALANCE = "user_full_balance";
    public static final String USER_AVAILABLE_BALANCE = "user_available_balance";
    public static final String USER_BALANCE_ID = "user_balance_id";
    public static final String DONT_ASK_OVERLAY = "dont_ask_overlay";
    public static final String FLOATING_ORDER_WINDOW_X_POS = "floating_order_window_x_pos";
    public static final String FLOATING_ORDER_WINDOW_Y_POS = "floating_order_window_y_pos";
    public static final String FAVORITE_CONTACTS = "favorite_contacts";
    public static final String SUCCESS_ADD_TO_FAV_REQUESTED = "succcess_add_to_fav_requested";
    public static final String TOAST_MESSAGE = "toast_message";
    public static final String INTRO_SHOWN = "intro_shown";
    public static final String INSTAGRAM_CONNECT_SUCCESS = "instagram_connect_success";
    public static final String INSTAGRAM_ALREADY_CONNECTED = "instagram_already_connected";
    public static final String INSTAGRAM_CONNECTED = "instagram_connected";
    public static final String REQUEST_PERMISSION_WITH_CALL = "request_permission_with_call";
    public static final String PACKAGE_ID = "package_id";
    public static final String ADDITIONAL_DATA = "additional_data";
    public static final String TOKEN = "token";
    public static final String HASH = "hash";
    public static final String SCROLL_TO_ITEM = "scroll_to_item";
    public static final String RECEIVE_PUSH = "receive_push";
    public static final String SHOW_NOTIFICATION = "show_notification";
    public static final String SHOW_SMART_NOTIFICATION = "show_smart_notification";
    public static final String ACTION = "action";
    public static final String OPEN_SUPPORT = "open_support";
    public static final String USER_TARIFF = "user_tariff";
    public static final String CURRENT_USER_TARIFF = "current_user_tariff";
    public static final String OPEN_PROFILE = "open_profile";
    public static final String LOCATION_DETECT_ERROR = "location_detect_error";
    public static final String RED_SNACKBAR = "red_snackbar";
    public static final String RUN_ONE_APP = "show_loading";
    public static final String OPEN_SERVICE_URL = "open_service_url";
    public static final String SERVICES_LIST = "services_list";
    public static final String HAS_LOCAL_DATA = "has_local_data";
    public static final String CONTACTS_EXPANDED_MENU_SHOWN = "contacts_expanded_menu_shown";
    public static final String RUN_DEACTIVATE_USSD_CODE = "run_deactivate_ussd_code";
    public static final String RUN_ACTIVATE_USSD_CODE = "run_activate_ussd_code";
    public static final String LOCAL_DATA_LOCALE = "local_data_locale";
    public static final String VERSION_CODE = "version_code";
    public static final String VERSION_UPDATED_AT_MILLIS = "version_updated_at_millis";
    public static final String MEGACOM_SERVICES_ADS_STR = "megacom_services_ads_str";
    public static final String MEGACOM_TARIFFS_ADS_STR = "megacom_tariffs_ads_str";
    public static final String OPEN_MY_PROFILE = "open_my_profile";
    public static final String OPEN_MEGACOM_PAGE = "open_megacom_page";
    public static final String JUST_AUTHORIZED = "just_authorized";
    public static final String SHOW_FLOATING_AD_EXPLANATION = "show_floating_ad_explanation";
    public static final String OPEN_OVERLAY_PERMISSION_PAGE = "open_overlay_permission_page";
    public static final String REQUEST_PROCESS_OUTGOING_CALL_PERMISSION = "request_process_outgoing_call_permission";
}